# Generated by Django 3.2.5 on 2021-08-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_draw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizedraw',
            name='winners',
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('prize_draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_prize_draw', to='app_draw.prizedraw')),
            ],
        ),
    ]
