# Generated by Django 3.2.5 on 2021-08-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_draw', '0002_auto_20210808_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizedraw',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
